spring.application.name=voice-notes-backend
spring.config.import=optional:classpath:application-local.properties

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MySQL Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/voxnote?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=${JWT_SECRET:}
jwt.expiration=86400000

# Free Tier AI Keys
assemblyai.api.key=${ASSEMBLYAI_KEY:}
gemini.api.key=${GEMINI_KEY:}
audio.storage.path=uploads/

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
